### ISSUE TITLE
Problem replying inside a message

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#119]
@goofy-bz reported he was unable to add text inside original message when replying to a message. Adding new lines keep the blockquote. This is a regression.

**Comment by poupotte** [comment]
I can't reproduce this issue.

**Comment by poupotte** [comment]
@goofy-bz, we have published a new version, I've you still this problem ?

**Comment by goofy-bz** [comment]
I have updated my cozymail and just made a series of tests with reply-to reply-all and fwd
1. Yes the problem still occurs :s
2. But *not always*: some messages make it impossible to write outside of the "quote" blue bar (even when hitting the RETURN key fiercely), some messages are just as easy to reply-to as expected, pressing return key once is enough to write outside quoted text.
3. I suppose this may help to catch the bug: when prob occurs a pink-backgrounded streak appears and tells:  
**Une erreur est survenue : Message contains bare newlines**

**Comment by clochix** [comment]
In fact, we have fixed the bug on master branch but not updated the version, so the update isn't available yet. Sorry.

**Comment by clochix** [comment]
@goofy-bz you should now be able to update the app and give it a try.

**Comment by clochix** [comment]
@goofy-bz any news ?

**Comment by goofy-bz** [comment]
I thinks there remain various strange behaviours.
0. sometimes striking the ENTER key brings a line break as expected and I can write outside quote block
0.1 In this case I notice there are two or three line breaks when just one is enough for my usage.
0.2 cursor position to allow me to write anything sometimes jump down the quote block instead of breaking the line at the wanted location

1. On most messages, as soon as I strike ENTER within a quoted block (my usage being: i want to write something just beneath one quoted line), there appears a pink-backgrouded message "Une erreur est survenue : Message contains bare newlines"
1.1 sometimes the message appears even though I did  not strike on ENTER key, but just clicked somewhere to drop the cursor position.

2. On some messages, after clicking on "reply" "reply all" or "transfer" icons 
a) quotation blue line appears
(/me doing nothing at all during est. 5 to 10 seconds)
b) quotation blue line *disappears* 

I know the various "sometimes" and "some messages" are not sufficient hints to understand what is going wrong. I will have more time to test methodically this whimsical app by the end of this week.

keep rolling folks!

**Comment by clochix** [comment]
@goofy-bz Having a new look at this issue, I found that "Message contains bare newlines" is another error, that seems to not be related to this one. It means that your IMAP server is strict on message format, and we try to save a badly formatted draft.

Have you seen the error recently ?

(FTR, every line of the message *must* end with CRLF, if one is missing, some servers will throw an error)

**Comment by frankrousseau** [comment]
I have the same problem. I can't remove the answer sideline when I reply in a middle of a message sometimes. Moreover the recipient see tabulations instead of ">" as sidelines.

**Comment by goofy-bz** [comment]
Here is a screenshot with a Reply-to mail (same prob not hit yet with Forward-to mails)

https://framapic.org/Q3q8lXRHsdWk/qd88lM0P

[sidenote : the image upload system on this very comment is a bit failing for me, I cannot send a <100 Ko image without the moron pretending it must be smaller than 10MB]

**Comment by frankrousseau** [comment]
I fixed my tabulation problem in this PR https://github.com/cozy/cozy-emails/pull/257

**Comment by poupotte** [comment]
@goofy-bz , is it fixed for you ?

**Comment by goofy-bz** [comment]
yes m'dam, I just tested and it seems to be fixed. Thanks!

**Comment by poupotte** [comment]
Thanks @goofy-bz, @clochix and @frankrousseau
