### ISSUE TITLE
Remove animations when displaying a message

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#122]
When I click on a message to read it, I don't have a consistent behavior on the way it is displayed. Sometimes, it slides from the right sometimes, it just changes the message. 

I will try to explain it better later. I open the issue to initiate the conversation about this.

**Comment by clochix** [comment]
I'm aware of this behavior, and know the reasoning behind it (when the right pan isn't shown, it slides on open. Then, messages are just updated inside the pane).

I would suggest removing the sliding effect to be more consistent.

@jsilvestre, any objection?

**Comment by clochix** [comment]
Ping @frankrousseau, what about removing the sliding effect when opening the right panel?

**Comment by frankrousseau** [comment]
Yes remove it! Common operation like opening an email should be as fast as possible.

**Comment by poupotte** [comment]
Message displaying is better without animations. Thanks @clochix .

it will be available in ** version 0.6.8 **

**Comment by frankrousseau** [comment]
The animation is still there.

**Comment by poupotte** [comment]
Yes, it stay a little animation during mail openning for the first time, I didn't see it.

**Comment by jsilvestre** [comment]
I have found references to the opening animations in the code:
* https://github.com/cozy/cozy-emails/blob/master/client/app/styles/_layout.styl#L93-L104
* https://github.com/cozy/cozy-emails/blob/master/client/app/styles/_message-list.styl#L13-L15
* https://github.com/cozy/cozy-emails/blob/master/client/app/styles/_compose.styl#L9-L11

**Comment by clochix** [comment]
Thanks a lot @jsilvestre, I forgot to remove this one.
I agree with you, I don't see any difference.
I just committed, the removal, will be in my next PR.

**Comment by frankrousseau** [comment]
@clochix Do not forget to not make too big PR.

**Comment by poupotte** [comment]
Effectively,  animations still exists but they're fast and if you don't know where they come from, I'm not sure is in our priority. I propose to put this issue in our backlog (not again in our next sprint). What do you think @frankrousseau ?

**Comment by frankrousseau** [comment]
Ok.
