### ISSUE TITLE
Infinite scroll is broken when displaying conversations

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#271]
In a mailbox, I have only one conversation, with 5 messages.
The “Load more messages” link is displayed, because it thinks we are only displaying one out five messages.

**Comment by clochix** [comment]
I made a fix that sums up the number of messages inside each conversation.
It's better, but still false, because if some messages inside the conversation are in other malboxes, the sum will be wrong. We should also compute (server side ?) the number of messages of the conversation that are inside the current mailbox. /ping @aenario

**Comment by aenario** [comment]
How about checking for the link : next in the answer instead of counting things ?

**Comment by clochix** [comment]
Ok, I'll try to remove the code that count messages and see if it works. Otherwise, I'll come back to you.

**Comment by clochix** [comment]
As a side effect of working on filtering, I found, at last, why using the link didn't work ☺

**Comment by clochix** [comment]
@poupotte I updated the code used to determine if there are more messages to show, it should now be simpler and works in more cases. Crossing fingers.

**Comment by poupotte** [comment]
It seems still broken :(

If I delete several messages/conversations, it displays 'This is the end of the road' instead of retrieve next messages.

**Comment by poupotte** [comment]
Infinite scrool works for me. Thanks @clochix  and @aenario.
