### ISSUE TITLE
Don't display removed message in conversation

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#284]

**Comment by clochix** [comment]
What shall we do when displaying messages in Draft and Trash folder ? Should we display the whole conversation they belong, or only the message itself.
The rules for conversation display make it a little bit harder to display conversations inside this folder, but it could make sense.

**Comment by clochix** [comment]
To sum up what we decided : hidding some messages in conversation is hard, because the number of messages inside the conversation would be wrong, so we display every messages, but add an icon on draft and deleted ones.
@m4dz should have a look on the icons.

**Comment by jsilvestre** [comment]
What is left in this issue? I feel like it's kinda working the way it's expected. I'd add a more visible thing that just the icon to show the message has been deleted (like an color overlay). What do you think?

**Comment by m4dz** [comment]
I think the icon is a good way but can be easily surrounded by an overlay, like a pattern on the header, suggesting the mail is _disabled_. Good suggestion :smile:.

**Comment by aenario** [comment]
This should be closed now (deleted messages are not shown in conversation anymore).

**Comment by poupotte** [comment]
Mmmm... no, we can hide it, but currently, deleted messages in a conversation are still displayed.

**Comment by aenario** [comment]
Server OK, need to have same behaviour client in client.

**Comment by poupotte** [comment]
Thanks @jsilvestre , removed messages aren't display in a conversation :+1: 

However, number messages in list isn't up-to-date :/ . 
As an example : 
 * I open a conversation with 3 messages
 * I remove a message in this conversation
 * Message disappear
 * In message list, number messages for this conversation still indicates 3

**Comment by jsilvestre** [comment]
I know why: the counter is updated when the success message is displayed, whereas the message is hidden optimistically. I'm going to change the counter update to match the message status.

**Comment by jsilvestre** [comment]
A fix has been merged, is it better @poupotte?

**Comment by poupotte** [comment]
Thanks @jsilvestre , it works well in realtime but if I refresh my application, conversation counter is still wrong :(

**Comment by poupotte** [comment]
Sorry, it works on my test account. I have lots of others issues on my personnal account, I think my last problem is due to another issue. Thanks for your job :+1: !
