### ISSUE TITLE
cozy-emails fails to mark read messages as read and displays two empty red boxes

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-emails#443]
title says it all.

**Comment by frankrousseau** [comment]
Thank you @arthurlutz for reporting.

**Comment by poupotte** [comment]
@arthurlutz , we have published a new email version last Friday, have you still this issue ?

**Comment by arthurlutz** [comment]
No, my email accounts are still broken. I'm starting to believe that the best way out is a "reboot" approach : delete my configured accounts and re-add them to have a clean state. Or is this an issue you want to debug further ?

**Comment by clochix** [comment]
Hello @arthurlutz. If I remember, you're self hosted, so debuging further wouldn't be very easy. I think the best approach is to delete your account, wait a little bit to be sure everything is really deleted from CouchDB, and try to re-add your accounts. Let us know if it works better, otherwise we'll see what we can do to debug.
